Добавляет решение для 05-http-server-streams 01-files-server-get
js-tasks-ru/nodejs-20201126-2_s-spirkin pull request #5
Opened 2020-12-13 20:48 UTC by Oakerin

2020-12-13 20:57 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Файловый сервер - отдача файла
+ файл отдается по запросу
+ если файла нет - отдается 404
+ если путь вложенный - возвращается ошибка 400
```

Добавляю преподавателя (@RidgeA) для код-ревью, посмотрим что он скажет :)

2020-12-14 08:52 UTC, RidgeA requested changes

2020-12-14 08:52 UTC, RidgeA commented on 05-http-server-streams/01-file-server-get/server.js
> +        rs.on('readable', () => {
Использование события `readable` это достаточно низкоуровневый подход при работе со стримами
Попробуйте переделать на использование pipe метода, который более подходящий для данной ситуации.

2020-12-14 09:21 UTC, Oakerin commented on 05-http-server-streams/01-file-server-get/server.js
> +        rs.on('readable', () => {
Принято, сделаю

2020-12-14 17:33 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-12-14 18:45 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-12-14 19:54 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-12-14 21:04 UTC, jsru commented
Не удалось выполнить проверку решения, пожалуйста, убедитесь в том, что все тесты
            выполняются локально, а также проверьте, нет ли в решении отладочных вызовов console.log
            (в результате вызова тестов в консоли не должно быть никакого лишнего вывода).

2020-12-19 21:51 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Файловый сервер - отдача файла
+ файл отдается по запросу
+ если файла нет - отдается 404
+ если путь вложенный - возвращается ошибка 400
```
```diff
Файловый сервер - запись файла
+ возвращается ошибка 409 при создании файла, который есть
+ если тело запроса пустое файл не перезаписывается
+ успешное создание файла
+ файл не должен оставаться на диске при обрыве соединения
+ если путь вложенный - возвращается ошибка 400
- при попытке создания слишком большого файла - ошибка 413
```

2020-12-21 07:44 UTC, Oakerin commented
@RidgeA Антон, доброе утро.

Не могу понять, почему не проходит тест.
Получаю вот такую ошибку `ECONNABORTED` вместо ожидаемых `ECONNRESET`, `EPIPE`

![image](https://user-images.githubusercontent.com/24847717/102751472-df836980-4378-11eb-9c6b-e765a6c82ae6.png)

Не подскажешь, в чем может быть проблема?
Вроде как, поток на запись при ошибке `LIMIT_EXCEEDED` я закрываю, но это все равно не помогает.
Что интересно, пару раз при моей реализации все тесты проходили

![image](https://user-images.githubusercontent.com/24847717/102751770-70f2db80-4379-11eb-8e54-72f42168bf80.png)

2020-12-21 09:45 UTC, RidgeA approved these changes

2020-12-21 09:45 UTC, merged